# Use pre-built biocontainer as base
FROM quay.io/biocontainers/gerp:2.1--he1b5a44_1

################## METADATA ######################
LABEL maintainer="@juliahoglund"
LABEL version=2.1
LABEL gerp=2.1