#####################
##### Step one: #####
#####################

chromosomes:
	number: [ '19' ]
	karyotype: [ '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', 'X']

maf:
  46_amniotes_epo:
    path: '.././fulldata/'
    type: 'maf.gz'
    clean_maf: 'False'