#####################
##### Step one: #####
#####################


chromosomes:
  number: [ '18' ]
  karyotype: [ '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', 'X']

alignments:
  43_mammals.epo:
    path: 'resources/alignment/'
    type: 'maf.gz'
    clean_maf: 'True'
    ancestral_label: "Ancestor_Pig_Cow" 
      # Ancestor_Pig_Cow, Ancestor_Pig_Sheep, Ancestor_Pig_Horse, Ancestor_Pig_Elephant
    filter_order: "sus_scrofa,Ancestor_Pig_Cow,bos_taurus"
      # bos_taurus, ovis_aries_rambouillet, equus_caballus, loxodonta_africana
    exclude_patterns: [ "scaffold", "epo.Y" ] 
      # Files including these strings will not be processed
    name_species_interest: "sus_scrofa"
    chrom_prefix: "chr" # prefix of chromosome in sequence label: mm39.chr[CHR]
    # is this needed later if not in sort by chr?
    ancestor: "True"
    pre_sorted: "False"

mark_ancestor:
  ancestral_alignment: "43_mammals.epo"
  name_ancestor: 'Ancestor_Pig_Cow'
    # Ancestor_Pig_Cow, Ancestor_Pig_Sheep, Ancestor_Pig_Horse, Ancestor_Pig_Elephant
  sp1_tree_ab: 'Sscr'
  sp2_tree_ab: 'Btau'
    # Btau, Oram, Ecab, Lafr
  reference_genome: 'resources/genome/Sus_scrofa_ref.fa'

generate_variants:
  reference_genome_wildcard: "resources/genome/Sus_scrofa_ref{chr}.fa"
  population_vcf:  "pig/chr{chr}.fa" #resources/pop_freq... #ON ANNUNA
  derive:
    frequency_threshold: 0.9
  simulate:
    overestimation_factor: 5 
    # doublecheck later based on what this is   

stats_report:
  annotation: 'True'
  gff: 'resources/Sus_scrofa.Sscrofa11.1.111.chr.gff3.gz'
  prefix: 'resources/Sus_scrofa.Sscrofa11.1.111.chr'
  tree: 'resources/tree_43_mammals.nwk'
  ingroup: 'sus scrofa' # has to be small letters only
  outgroup: 'bos taurus'
    # bos taurus, ovis aries rambouillet, equus caballus, loxodonta africana
