##### GLOBAL SETTINGS #####
species_name: "sus_scrofa"
genome_version: "Sus_scrofa11.1"

##### PATHS #####
paths:
  resources: "resources/"
  reference_genome: "resources/genome/"
  alignments: "resources/alignment/"
  population_vcf: "resources/pop-level-VCF/"
  annotations: "resources/"

##### CHROMOSOME SETS #####
chromosomes:
  autosomes: [ '18' ]
  karyotype: [ '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', 'X']
  train: [ '1', '2', '3', '4', '5' ]
  score: [ '1', '2', '3', '4', '5' ]

##### ALIGNMENT SETTINGS #####
alignment:
  path: 'resources/alignment/'
  type: 'maf.gz'
  clean_maf: 'True'
  ancestral_label: "Ancestor_Pig_Cow" 
  filter_order: "sus_scrofa,Ancestor_Pig_Cow,bos_taurus"
    # all species needed / wanted for gerp computation need to be included here, as maf_order removes everything not in this list
    # Full species list: balaenoptera_musculus,bos_grunniens,bos_indicus_hybrid,bos_taurus,camelus_dromedarius,canis_lupus_dingo,canis_lupus_familiaris,capra_hircus,catagonus_wagneri,cavia_porcellus,cervus_hanglu_yarkandensis,chlorocebus_sabaeus,cricetulus_griseus_chok1gshd,delphinapterus_leucas,equus_caballus,felis_catus,gorilla_gorilla,homo_sapiens,loxodonta_africana,macaca_fascicularis,macaca_mulatta,marmota_marmota_marmota,microcebus_murinus,microtus_ochrogaster,monodon_monoceros,mus_caroli,mus_musculus,mus_pahari,mus_spretus,nomascus_leucogenys,oryctolagus_cuniculus,ovis_aries_rambouillet,pan_paniscus,pan_troglodytes,panthera_leo,panthera_pardus,peromyscus_maniculatus_bairdii,phocoena_sinus,physeter_catodon,rattus_norvegicus,rhinolophus_ferrumequinum,sciurus_vulgaris,sus_scrofa
  exclude_patterns: [ "scaffold", "epo.Y" ] 
  name_species_interest: "sus_scrofa"
  chrom_prefix: "chr" # prefix of chromosome in sequence label

##### ANCESTOR INFERENCE #####
mark_ancestor:
  name_ancestor: 'Ancestor_Pig_Cow'
  sp1_tree_ab: 'Sscr'
  sp2_tree_ab: 'Btau'
  reference_genome: 'resources/genome/Sus_scrofa_ref.fa'

##### VARIANT GENERATION #####
generate_variants:
  reference_genome_wildcard: "resources/genome/Sus_scrofa_ref_{chr}.fa"
  population_vcf: "resources/pop-level-VCF/chr{chr}.vcf"
  derive:
    frequency_threshold: 0.9
  simulate:
    overestimation_factor: 5

##### ANNOTATION SETTINGS #####
annotation:
  gerp:
    n_chunks: '30'
    tree: 'resources/tree_43_mammals.nwk'
  phast:
    tree: '(camelus_dromedarius,(catagonus_wagneri,sus_scrofa),(bos_taurus)(ovis_aries_rambouillet))'
    tree_species: "sus_scrofa|camelus_dromedarius|catagonus_wagneri|bos_taurus|ovis_aries_rambouillet"
    train_precision: "HIGH"
    phastCons_params: "--target-coverage 0.3 --expected-length 45 --rho 0.3"
    phyloP_params: "--method=LRT --mode=CONACC"
  vep:
    cache:
      directory: '$VEP_CACHE' # Environment variable or path like: resources/vep
      should_install: False # Set to True to auto-install VEP cache
      install_params: "--CACHE_VERSION 110 -s sus_scrofa -y Sscrofa11.1"

annotation_config:
  processing: "config/annot_processing_config.tsv"
  interactions: "config/annot_combinations_config.tsv"

##### SUMMARY REPORTS #####

stats_report:
  annotation: 'True'
  gff: 'resources/Sus_scrofa.Sscrofa11.1.111.chr.gff3.gz'
  gtf: 'resources/Sus_scrofa.Sscrofa11.1.111.chr.gtf.gz'
  is_gtf: 'False' # Set to True if using GTF instead of GFF
  prefix: 'resources/Sus_scrofa.Sscrofa11.1.111.chr'
  tree: 'resources/tree_43_mammals.nwk' # Consistent with annotation.gerp.tree
  ingroup: 'sus scrofa' # Must be lowercase
  outgroup: 'bos taurus'

##### MODEL TRAINING #####
model:
  n_folds: 5
  test_params:
    c: [0.1, 1.0, 10.0]
    max_iter: [100, 200]
  final_params:
    c: 10.0
    max_iter: 100
  column_subsets:
    All: "SPECIAL KEY, uses all columns"

##### COMPUTATIONAL RESOURCES #####
parallelization:
  whole_genome_positions_per_file: 500000

memory:
  dataset_mb: 80000
  scoring_mb: 90000

