#####################
##### Step one: #####
#####################


chromosomes:
  number: [ '18' ]
  karyotype: [ '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', 'X']

alignments:
  43_mammals.epo:
    path: 'alnFiles/'
    type: 'maf.gz'
    clean_maf: 'True'
    ancestral_label: "Ancestor_Pig_Cow"
    filter_order: "sus_scrofa,Ancestor_Pig_Cow,bos_taurus"
    exclude_patterns: [ "scaffold", "epo.Y" ] # Files including these strings will not be processed
    name_species_interest: "sus_scrofa"
    chrom_prefix: "chr" # prefix of chromosome in sequence label: mm39.chr[CHR]
    ancestor: "True"
    pre_sorted: "False"

mark_ancestor:
  ancestral_alignment: "43_mammals.epo"
  name_ancestor: 'Ancestor_Pig_Cow'
  sp1_tree_ab: 'Sscr'
  sp2_tree_ab: 'Btau'