
species_name: "elephas_maximus"

  realignment:
    alignment_reference: "eleMax/GCF_024166365.1_mEleMax1_primary_haplotype_genomic.fna.gz" 
    # combine this and the other one
    seq_path: "seqdir/"
    reference_genome: 'eleMax/GCF_024166365.1_mEleMax1_primary_haplotype_genomic.fna.gz'
    exclude_patterns: ['NW_']
    # todo: incorporate this


