# Use pre-built biocontainer as base
FROM quay.io/biocontainers/phast:1.9.7--h7eac25e_0

################## METADATA ######################
LABEL maintainer="@juliahoglund"
LABEL version=1.9.7
LABEL phast=1.9.7